spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: 192.168.178.85:9092

game:
  topic-name: game-of-three
  player1:
    name: Jackie
    topic: jack-attack
  player2:
    name: Tommy
    topic: toom-the-boom